# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: name-tests-test
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.780  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
#    -   id: python-no-log-warn
#-   repo: https://github.com/pycqa/flake8
#    rev: 3.8.2
#    hooks:
#    -   id: flake8
#-   repo: https://github.com/pycqa/bandit
#    rev: 1.6.2
#    hooks:
#    -   id: bandit
#-   repo: https://github.com/pycqa/pydocstyle
#    rev: 5.0.2
#    hooks:
#    -   id: pydocstyle
#-   repo: https://github.com/pycqa/pylint
#    rev: pylint-2.5.0
#    hooks:
#    -   id: pylint
#        args: [ '-E' ]
#-   repo: https://github.com/asottile/dead
#    rev: v1.3.0
#    hooks:
#    -   id: dead
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
    -   id: gitlint
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.9.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.2.0
    hooks:
    -   id: pip-compile
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
#-   repo: https://github.com/asottile/pyupgrade
#    rev: v2.6.1
#    hooks:
#    -   id: pyupgrade
#        args: [ '--py3-plus' ]
