language: python
dist: focal
python: "3.8"

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit


stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install pytest-cov
        - pip install poetry
        - poetry install -v
      script:
        - pytest --cov
