language: python
dist: focal
python: "3.8"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry
    - $HOME/.cache/pre-commit


stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      addons:
        apt:
          packages:
            - libgirepository1.0-dev
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install --verbose --extras "tui gui"
      script:
        - pytest -vv --cov=src

after_success:
  coveralls
